version: "3.8"

services:
  flask:
    build: .
    container_name: flask_app
    expose:
      - "5000"
    networks:
      custom_net:
        ipv4_address: 172.25.0.10

  nginx:
    image: nginx:latest
    container_name: nginx_ctf
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - flask
    networks:
      custom_net:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
